### ISSUE TITLE
merge newapi branch

### ISSUE THREAD

**Issue by beanumber** [beanumber/etl#14]
This will break `airlines` until I can fix it. 

@nicholasjhorton can you let me know what you are OK with me breaking `airlines` for a spell?

@cpsievert @nicholasjhorton Are you satisfied with the `newapi` branch? Please see the [README](https://github.com/beanumber/etl/tree/newapi)

**Comment by nicholasjhorton** [comment]
I'm fine with you breaking it for a spell.

Nick

> On Dec 17, 2015, at 12:21 PM, Ben Baumer notifications@github.com wrote:
> 
> This will break airlines until I can fix it.
> 
> @nicholasjhorton can you let me know what you are OK with me breaking airlines for a spell?
> 
> @cpsievert @nicholasjhorton Are you satisfied with the newapi branch? Please see the README
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton
