### ISSUE TITLE
naming of functions

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/etl#16]
If I'm understanding things correctly there are:

etl()
etl_create()
etl_update()
etl_extract(), and
etl_cleanup() 

functions in the etl framework.  Might it make sense to change etl() to etl_init() and etl_create() to etl_populate()?  The others feel more self explanatory (but "etl()" by itself doesn't make sense).

**Comment by beanumber** [comment]
There is also `etl_transform` and `etl_load`. 

`etl` is the constructor. @hadley [likes constructors](http://adv-r.had.co.nz/OO-essentials.html#s3), so I am inclined to keep that. 

The four main functions in the pipeline are:

```
etl_extract()
etl_transform()
etl_load()
etl_cleanup()
```

The two functions `etl_create` and `etl_update` are just wrappers to that pipeline. @cpsievert also favors junking the wrapping functions. I'm happy to consider re-naming either, but `etl_populate` sounds more like a replacement for `etl_load` than `etl_create`.
