### ISSUE TITLE
add option to make etl_create() and etl_load() more verbose if desired

### ISSUE THREAD

**Issue by nicholasjhorton** [beanumber/etl#5]

**Comment by beanumber** [comment]
Sure thing, what kind of information do you want to see?

**Comment by nicholasjhorton** [comment]
Can it echo the commands used to download the tables and SQL code that gets generated?

Just a thought,

Nick

> On Nov 25, 2015, at 3:39 PM, Ben Baumer notifications@github.com wrote:
> 
> Sure thing, what kind of information do you want to see?
> 
> —
> Reply to this email directly or view it on GitHub.

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
I added an echo argument to `dbGetQuery_safe()` that can be passed through either `etl_create()`, `etl_update()`, or `etl_load()`.
