### ISSUE TITLE
installing etl package from GitHub error 

### ISSUE THREAD

**Issue by niannucci** [beanumber/etl#54]
install_github("beanumber/etl")
> Error : object ‘use_package’ is not exported by 'namespace:devtools'

**Comment by cZachJohnson** [comment]
It appears to be a package dependency issue with devtools and usethis. The function use_package comes from the package usethis and not from devtools depending on the version of each package that you have.

**Comment by beanumber** [comment]
I think I got this fixed. Thanks @niannucci  and @cZachJohnson !
