### ISSUE TITLE
usethis release makes a test fail

### ISSUE THREAD

**Issue by jennybc** [beanumber/etl#59]
We are in the process of releasing usethis v1.6.0.

Although we did not see a problem with etl in our revdep checks, CRAN did. It appears to be due to a brittle test where the success of some etl call is judged by testing for some exact text in messaging emitted by usethis.

Below is what CRAN's auto-check service shows.

Can you rework your test to pass against dev usethis? I don't think this will hold up the usethis release, but let's fix it soon-ish anyway.  Ideally your tests wouldn't rely on, e.g., the exact behaviour of another package re: messaging.

---

Package: etl
Check: tests
New result: ERROR
    Running â€˜testthat.Râ€™ [2s/2s]
  Running the tests in â€˜tests/testthat.Râ€™ failed.
  Complete output:
    > library(testthat)
    > library(etl)
    Loading required package: dplyr
    
    Attaching package: 'dplyr'
    
    The following object is masked from 'package:testthat':
    
        matches
    
    The following objects are masked from 'package:stats':
    
        filter, lag
    
    The following objects are masked from 'package:base':
    
        intersect, setdiff, setequal, union
    
    > 
    > test_check("etl")
    â”€â”€ 1. Failure: create ETL works (@test-etl.R#114)  â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    `create_etl_package\(path, open = FALSE\)` does not match "active project".
    Actual value: "Package: scorecard\\nTitle: What the Package Does \(One Line, Title Case\)\\nVersion: 0\.0\.0\.9000\\nAuthors@R \(parsed\):\\n    \* First Last <first\.last@example\.com> \[aut, cre\] \(YOUR-ORCID-ID\)\\nDescription: What the package does \(one paragraph\)\.\\nLicense: `use_mit_license\(\)`, `use_gpl3_license\(\)` or friends to pick a\\n    license\\nEncoding: UTF-8\\nLazyData: true\\nRoxygen: list\(markdown = TRUE\)\\nRoxygenNote: 7\.0\.0"
    
    â•â• testthat results  â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    [ OK: 27 | SKIPPED: 2 | WARNINGS: 0 | FAILED: 1 ]
    1. Failure: create ETL works (@test-etl.R#114) 
    
    Error: testthat unit tests failed
    Execution halted

**Comment by beanumber** [comment]
Thanks, I will fix it. Please proceed!
