### ISSUE TITLE
Figure out what to do with extra DBI functionality

### ISSUE THREAD

**Issue by beanumber** [beanumber/etl#9]
[My pull request](https://github.com/rstats-db/DBI/pull/34) to add `dbCreateIndex()` was denied from DBI. 

So now that functionality will probably move here. 

The [pull request for `dbRunScript()`](https://github.com/rstats-db/DBI/pull/45) is still pending...

**Comment by cpsievert** [comment]
I like the idea of a **DBIadmin** package and having **etl** import it.

**Comment by beanumber** [comment]
It seems like DBI is undergoing development, but maybe this would help push them forward.

**Comment by beanumber** [comment]
This seems to all be in `dplyr` now, with the exception of `dbRunScript`.
